# -*- coding: utf-8 -*-
"""
构建 IT 会议英语练习库。

输入（唯一源头，人工维护）：
    sources/dialogues.json      分组定义 + 每段对话的元数据与台词

输出（全部为生成物，不要手改）：
    data/catalog.js             索引，浏览器用 (window.CATALOG)
    data/talks.js               全部台词与时间轴，浏览器用 (window.TALKS)
    index.html                  练习库首页
    player.html                 播放器，按 #编号 切换素材
    <mediaRoot>/<dir>/<name>.html   每段素材的独立页（同名同目录，方便直接用）

用法：
    python tools/build.py           构建
    python tools/build.py --check   只校验，不写任何文件
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "sources", "dialogues.json")
PHRASES = os.path.join(REPO, "sources", "phrases.json")
MARK = "<!-- generated by tools/build.py -->"

# ---------- 编稿体检（方案 §4 / §6） ----------

# 判负词表：教科书写法，出现即不合格
BANNED = ["i would like to", "in order to", "furthermore", "moreover",
          "i am writing to", "please find", "kindly note that", "as per",
          "it is imperative", "we should note that"]

# 印度英语特征（句法层，语音层写在 phrases.note 里）
INDIAN_PATS = [
    r"\bi have a doubt\b", r"\bhave a doubt\b", r"\bdoubts?\s+on\b",
    r"\bright\?\s*$", r"\bnot there\b", r"\bonly[.!]?\s*$",
    r"\brevert back\b", r"\bdo the needful\b", r"\bprepone\b", r"\bdo one thing\b",
    r"\b(?:am|is|are|was|were) having\b", r"\b(?:am|is|are) doing\b",
    r"\bwill be doing\b", r"\bwere thinking\b", r"\bnot showing\b", r"\bitself\b",
]

MARKERS = [r"\bso\b", r"\bokay\b", r"\bok\b", r"\balright\b", r"\bwell\b", r"\banyway\b",
           r"\bi mean\b", r"\byou know\b", r"\bactually\b", r"\bbasically\b", r"\bhonestly\b",
           r"\bto be fair\b", r"\bthen\b", r"\bnow\b", r"\bright\b"]

HEDGES = [r"\bkind of\b", r"\bsort of\b", r"\broughly\b", r"\babout\b", r"\bprobably\b",
          r"\bmaybe\b", r"\bi think\b", r"\bi guess\b", r"\bmight\b", r"\bseems?\b",
          r"\blooks like\b", r"\bi'd say\b", r"\bat least\b", r"\bfor now\b", r"\btop\b"]

SENT_SPLIT = re.compile(r"(?<=[.!?\u2026])\s+")


def sentences(text: str) -> list[str]:
    """切句并保留句末标点 —— only / right? 这类印度英语模式依赖句尾锚点。"""
    out = []
    for chunk in SENT_SPLIT.split(text.strip()):
        chunk = chunk.strip()
        if re.search(r"[A-Za-z0-9']", chunk):
            out.append(chunk)
    return out


def resolve_phrases(it: dict, bank: dict) -> list[dict]:
    """把段里的表达清单解析成 [{id, level}]。
    level 默认取表达库，允许写成 'pid:extra' / 'pid:core' 在本段覆盖
    —— 这样才能保证每段 ★ 核心表达不超过 3 个。"""
    out = []
    for spec in it.get("phrases", []):
        if ":" in spec:
            pid, ov = spec.split(":", 1)
        else:
            pid, ov = spec, None
        out.append({"id": pid, "level": ov or bank.get(pid, {}).get("level", "extra")})
    return out


def pid_of(spec: str) -> str:
    return spec.split(":", 1)[0]


def words_of(text: str) -> int:
    return len(re.findall(r"[A-Za-z0-9']+", text))


def hits(text: str, pats: list[str]) -> int:
    low = text.lower()
    return sum(len(re.findall(p, low)) for p in pats)


def load_bank() -> dict:
    if not os.path.isfile(PHRASES):
        return {}
    return {p["id"]: p for p in json.load(open(PHRASES, encoding="utf-8"))["phrases"]}


def metrics(doc: dict) -> dict:
    """逐段与全库的编稿体检结果。"""
    bank = load_bank()

    seen: dict[str, list[str]] = {}
    rows = []
    for it in doc["dialogues"]:
        lines = [c for c in it["lines"] if c.get("sp") != "旁白"]
        sents, sents_all = [], []
        for c in lines:
            sents_all += sentences(c["en"])
        sents = sents_all
        # 句长只统计「≥3 词」的句子：Okay. / Right. / Me. 这类应声词不算句子，
        # 否则口语材料会被系统性低估（真实口语语料库同样这样处理）。
        full = [s for s in sents if words_of(s) >= 3] or [""]
        nw = sum(words_of(s) for s in full)
        n = len(full)
        short = sum(1 for s in sents if words_of(s) < 8)
        blob = " ".join(c["en"] for c in lines)
        resolved = resolve_phrases(it, bank)
        core = [p["id"] for p in resolved if p["level"] == "core"]
        extra = [p["id"] for p in resolved if p["level"] != "core"]
        rec = {
            "id": it["id"], "title": it["title"], "group": it["group"],
            "dur": float(it.get("duration") or 0),
            "wps": nw / n, "short": short / (len(sents) or 1), "nsent": len(sents),
            "markers": hits(blob, MARKERS), "hedges": hits(blob, HEDGES),
            # 印度英语特征按「句」匹配，因为 only / right? 等模式依赖句尾锚点
            "indian": sum(hits(s, INDIAN_PATS) for s in sents),
            "banned": hits(blob, BANNED),
            "core": core, "extra": extra,
            "baseline": it["group"] == "baseline",
        }
        rows.append(rec)
        for p in resolved:
            seen.setdefault(p["id"], []).append(it["id"])

    return {"rows": rows, "seen": seen, "bank": bank}


def print_metrics(doc: dict, check_rows: bool) -> int:
    """打印体检报告；返回硬失败条数。"""
    m = metrics(doc)
    rows, seen, bank = m["rows"], m["seen"], m["bank"]
    graded = [r for r in rows if not r["baseline"]]
    fails = []

    print("\n=== 编稿体检（baseline 段不计入） ===")
    print(f"{'段':6s}{'时长':>7s}{'词/句':>7s}{'短句%':>7s}{'语篇':>5s}{'模糊':>5s}{'印度':>5s}{'负词':>5s}  ★核心")
    for r in graded:
        flags = []
        if r["dur"] > 120: flags.append("超2分钟")
        if not (5.0 <= r["wps"] <= 9.5): flags.append("词/句越界")
        if r["short"] < 0.5: flags.append("短句不足")
        if r["indian"] < 1: flags.append("缺印度特征")
        if r["banned"]: flags.append("判负词")
        if not (1 <= len(r["core"]) <= 3): flags.append("★数越界")
        if flags:
            fails.append(f"{r['id']} " + "、".join(flags))
        print(f"{r['id']:6s}{r['dur']:6.1f}s{r['wps']:7.1f}{r['short']*100:6.0f}%"
              f"{r['markers']:5d}{r['hedges']:5d}{r['indian']:5d}{r['banned']:5d}  "
              f"{', '.join(r['core']) or '-'}")

    # 全库汇总
    all_s = []
    for it in doc["dialogues"]:
        if it["group"] == "baseline":
            continue
        for c in it["lines"]:
            if c.get("sp") != "旁白":
                all_s += sentences(c["en"])
    full = [s for s in all_s if words_of(s) >= 3] or [""]
    print(f"\n合计 {len(graded)} 段 / {len(all_s)} 句（其中 ≥3 词的完整句 {len(full)} 句）")
    print(f"  平均句长 {sum(words_of(s) for s in full)/len(full):.1f} 词（目标 6–9，不含应声句）  "
          f"短句(<8词)占比 {sum(1 for s in all_s if words_of(s)<8)/max(1,len(all_s))*100:.0f}%（目标 ≥50%）")

    occ = {pid: len(v) for pid, v in seen.items()}
    once = sum(1 for v in occ.values() if v == 1)
    thr = sum(1 for v in occ.values() if v >= 3)
    tot = len(occ) or 1
    print(f"  表达 {tot} 个 · 平均复现 {sum(occ.values())/tot:.2f} 次 · "
          f"只出现 1 次 {once/tot*100:.0f}% · 出现 ≥3 次 {thr/tot*100:.0f}%")
    print("  （对照：baseline 旧素材平均 1.01 次、只出现一次 99%）")

    due = [f"{pid} {bank[pid]['en']}（{occ[pid]}/{bank[pid]['target']}）"
           for pid in bank if occ.get(pid, 0) < 3]
    if due:
        print(f"\n--- 复现不足 3 次的表达（{len(due)} 个，试产阶段正常） ---")
        for d in due:
            print("  ·", d)

    if fails:
        print(f"\n硬指标未达标 {len(fails)} 段：")
        for f in fails:
            print("  ✗", f)
    else:
        print("\n硬指标：全部通过。")
    return len(fails)


PAGE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>{title}</title>
<link rel="stylesheet" href="{root}assets/app.css">
</head>
<body data-mode="{mode}" data-root="{root}"{extra}>
{MARK}
<div id="app"></div>
<script src="{root}data/catalog.js"></script>
<script src="{root}data/talks.js"></script>
<script src="{root}data/phrases.js"></script>
<script src="{root}assets/app.js"></script>
</body>
</html>
"""


def load_source() -> dict:
    with open(SRC, encoding="utf-8") as f:
        return json.load(f)


def media_dir_of(item: dict, media_root: str) -> str:
    return os.path.join(REPO, media_root, item["dir"])


def validate(doc: dict) -> list[str]:
    """返回问题列表；空列表表示通过。"""
    errs: list[str] = []
    media_root = doc.get("mediaRoot", "audio")
    gids = [g["id"] for g in doc.get("groups", [])]
    items = doc.get("dialogues", [])

    if len(gids) != len(set(gids)):
        errs.append("分组 id 有重复")
    if not items:
        errs.append("dialogues 为空")

    ids = [x["id"] for x in items]
    dup = {i for i in ids if ids.count(i) > 1}
    if dup:
        errs.append(f"对话 id 重复：{sorted(dup)}")

    for it in items:
        tag = f"[{it.get('id', '?')}] {it.get('title', '')}"
        for k in ("id", "group", "title", "dir", "audio", "duration", "lines"):
            if k not in it:
                errs.append(f"{tag} 缺少字段 {k}")
        if it.get("group") not in gids:
            errs.append(f"{tag} 的 group={it.get('group')!r} 未在 groups 里定义")

        base = it["audio"].rsplit(".", 1)[0]
        folder = os.path.join(REPO, media_root, it["dir"])
        need = [it["audio"], base + ".vtt", base + ".en.vtt", base + ".zh.vtt"]
        for name in need:
            p = os.path.join(folder, name)
            if not os.path.isfile(p):
                errs.append(f"{tag} 缺少媒体文件 {os.path.relpath(p, REPO)}")

        lines = it.get("lines", [])
        if not lines:
            errs.append(f"{tag} 没有台词")
        for i, c in enumerate(lines, 1):
            for k in ("sp", "en", "zh", "start", "end"):
                if k not in c:
                    errs.append(f"{tag} 第 {i} 句缺少字段 {k}")
                    break
            else:
                if c["end"] <= c["start"]:
                    errs.append(f"{tag} 第 {i} 句时间轴异常 start>=end")
                if i > 1 and c["start"] < lines[i - 2]["end"] - 0.02:
                    errs.append(f"{tag} 第 {i} 句与上一句时间轴重叠")
        if lines and abs(lines[-1]["end"] - it["duration"]) > 0.5:
            errs.append(f"{tag} 末句结束 {lines[-1]['end']:.2f}s 与 duration {it['duration']:.2f}s 不符")
    return errs


def catalog_of(doc: dict, bank: dict | None = None) -> dict:
    bank = bank or {}
    items = []
    for it in doc["dialogues"]:
        items.append({
            "id": it["id"],
            "group": it["group"],
            "seq": it.get("seq"),
            "title": it["title"],
            "scene": it.get("scene", ""),
            "dir": it["dir"],
            "audio": it["audio"],
            "accent": it.get("accent", ""),
            "tags": it.get("tags", []),
            "roles": it.get("roles", []),
            "duration": round(float(it["duration"]), 2),
            "sentences": len(it.get("lines", [])),
            "domain": it.get("domain", ""),
            "series": it.get("series", ""),
            "part": it.get("part"),
            "parts": it.get("parts"),
            "stage": it.get("stage", ""),
            "premise": it.get("premise", ""),
            "phrases": resolve_phrases(it, bank),
        })
    items.sort(key=lambda x: (x["group"], x["seq"] if x["seq"] is not None else 0, x["id"]))
    return {
        "version": doc.get("version", 1),
        "mediaRoot": doc.get("mediaRoot", "audio"),
        "groups": doc.get("groups", []),
        "series": doc.get("series", []),
        "items": items,
    }


def talks_of(doc: dict) -> dict:
    return {it["id"]: {"lines": it["lines"]} for it in doc["dialogues"]}


def phrases_of(doc: dict) -> dict:
    """表达库 + 实际出现位置，供页面做「表达互引」与「已听 N 次」。"""
    bank = {k: dict(v) for k, v in load_bank().items()}
    for it in doc["dialogues"]:
        for spec in it.get("phrases", []):
            pid = pid_of(spec)
            if pid not in bank:
                bank[pid] = {"id": pid, "en": pid, "zh": "", "layer": "?", "level": "extra",
                             "target": 0, "note": ""}
            bank[pid].setdefault("seen", [])
            if it["id"] not in bank[pid]["seen"]:
                bank[pid]["seen"].append(it["id"])
    return {"phrases": bank}



def write(path: str, text: str, check: bool) -> tuple[str, int]:
    rel = os.path.relpath(path, REPO)
    if not check:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    return rel, len(text.encode("utf-8"))


def prune(doc: dict, check: bool) -> list[str]:
    """删掉不在索引里、且是 build.py 生成的条目页。"""
    media_root = doc.get("mediaRoot", "audio")
    keep = {os.path.normpath(os.path.join(REPO, media_root, it["dir"],
                                          it["audio"].rsplit(".", 1)[0] + ".html"))
            for it in doc["dialogues"]}
    removed = []
    for root, _dirs, files in os.walk(os.path.join(REPO, media_root)):
        for fn in files:
            if not fn.endswith(".html"):
                continue
            p = os.path.normpath(os.path.join(root, fn))
            if p in keep:
                continue
            try:
                head = open(p, encoding="utf-8").read(400)
            except OSError:
                continue
            if MARK in head:
                removed.append(os.path.relpath(p, REPO))
                if not check:
                    os.remove(p)
    return removed


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="只校验，不写文件")
    args = ap.parse_args()

    doc = load_source()
    errs = validate(doc)
    if errs:
        print("校验未通过：")
        for e in errs:
            print("  ✗", e)
        return 1
    print(f"校验通过：{len(doc['dialogues'])} 段对话 / "
          f"{len(doc['groups'])} 个分组 / {sum(len(x['lines']) for x in doc['dialogues'])} 句")

    cat = catalog_of(doc, load_bank())
    talks = talks_of(doc)
    ph = phrases_of(doc)
    out: list[tuple[str, int]] = []

    out.append(write(os.path.join(REPO, "data", "catalog.js"),
                     "window.CATALOG = " + json.dumps(cat, ensure_ascii=False, separators=(",", ":")) + ";\n",
                     args.check))
    out.append(write(os.path.join(REPO, "data", "talks.js"),
                     "window.TALKS = " + json.dumps(talks, ensure_ascii=False, separators=(",", ":")) + ";\n",
                     args.check))
    out.append(write(os.path.join(REPO, "data", "phrases.js"),
                     "window.PHRASES = " + json.dumps(ph, ensure_ascii=False, separators=(",", ":")) + ";\n",
                     args.check))

    out.append(write(os.path.join(REPO, "index.html"),
                     PAGE.format(title="IT 会议英语 · 练习库", mode="index", root="", extra="",
                                 MARK=MARK), args.check))
    out.append(write(os.path.join(REPO, "player.html"),
                     PAGE.format(title="播放器 · IT 会议英语", mode="player", root="", extra="",
                                 MARK=MARK), args.check))

    media_root = doc.get("mediaRoot", "audio")
    for it in doc["dialogues"]:
        parts = it["dir"].split("/")
        root = "../" * (len(parts) + 1)
        base = it["audio"].rsplit(".", 1)[0]
        p = os.path.join(REPO, media_root, it["dir"], base + ".html")
        out.append(write(p, PAGE.format(title=it["title"] + " · IT 会议英语", mode="item",
                                        root=root, extra=' data-id="' + it["id"] + '"',
                                        MARK=MARK), args.check))

    gone = prune(doc, args.check)
    print(("检查模式，未写入。" if args.check else "已生成："))
    for rel, n in out:
        print(f"  {rel:58s} {n/1024:7.1f} KB")
    if gone:
        print(("将清理 " if args.check else "已清理 ") + f"{len(gone)} 个过期条目页：")
        for g in gone:
            print("  -", g)
    total = sum(n for _, n in out)
    print(f"合计 {len(out)} 个文件 / {total/1024:.1f} KB")

    if args.check:
        return 1 if print_metrics(doc, True) else 0
    print_metrics(doc, False)
    return 0


if __name__ == "__main__":
    sys.exit(main())
